import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa">
      <head>
        <link
          rel="icon"
          type="image/jpg"
          sizes="32x32"
          href="http://nirvanacafe.ir/uploads/logo.webp"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no"
        />
        <title>نیروانا کافه</title>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
